---
- name: Set facts for the main role
  ansible.builtin.set_fact:
    _docker_compose_systemd_service_prefix: "{{ docker_compose_systemd_service_systemd_dir + '/' + docker_compose_systemd_service_root_service_name + '@' }}"

- name: Check to see if directory exists
  ansible.builtin.file:
    path: "{{ docker_compose_systemd_service_working_path }}"
    owner: "{{ docker_compose_systemd_service_user }}"
    group: "{{ docker_compose_systemd_service_group }}"
    mode: "0600"

- name: Find Docker Compose
  ansible.builtin.include_tasks: docker-compose.yaml

- name: Copy the docker service template
  block:
    - name: Copy the docker service template
      when: docker_compose_systemd_service_docker_compose_path is defined
      ansible.builtin.template:
        src: docker-compose.service.ansible.j2
        dest: "{{ _docker_compose_systemd_service_prefix + '.service' }}"
        owner: "{{ docker_compose_systemd_service_user }}"
        group: "{{ docker_compose_systemd_service_group }}"
        mode: "0644"
      notify: reload systemd
