---

rewardsfarmer_root_dir: /etc/docker/compose/rewardsfarmer
rewardsfarmer_systemd_enabled: true
rewardsfarmer_servicename: rewardsfarmer
rewardsfarmer_timer_hours: 13
rewardsfarmer_timer_delay: 0
rewardsfarmer_accounts: {}
