---
- name: Ensure the directory exists
  ansible.builtin.file:
    path: "{{ rewardsfarmer_root_dir }}"
    owner: root
    group: root
    mode: "0600"

- name: Copy the accounts file
  ansible.builtin.copy:
    content: "{{ rewardsfarmer_accounts | to_nice_json }}"
    dest: "{{ rewardsfarmer_root_dir }}/accounts.json"
    owner: root
    group: root
    mode: "0600"
  when: rewardsfarmer_accounts.accounts | length > 0

- name: Setup the SystemD components
  when: rewardsfarmer_systemd_enabled | default(true) | bool
  block:
    - name: Enable the rewardsfarmer service
      ansible.builtin.systemd:
        name: docker-compose@{{ rewardsfarmer_servicename }}.service
        enabled: true
        masked: false
        state: started
      notify: reload systemd

    - name: Copy the docker service template
      ansible.builtin.template:
        src: docker-compose.service.timer.ansible.j2
        dest: /etc/systemd/system/docker-compose@{{ rewardsfarmer_servicename }}.timer
        owner: "{{ docker_compose_systemd_service_user }}"
        group: "{{ docker_compose_systemd_service_group }}"
        mode: "0644"
      notify: reload systemd

    - name: Enable the docker service timer
      ansible.builtin.systemd:
        name: docker-compose@{{ rewardsfarmer_servicename }}.timer
        enabled: true
        masked: false
        state: started
      notify: reload systemd
