---
- name: Ensure the directory exists
  ansible.builtin.file:
    path: "{{ rewardsfarmer_systemd_service_path }}"
    owner: root
    group: root
    mode: "0600"

- name: Copy the accounts file
  ansible.builtin.copy:
    content: "{{ rewardsfarmer_accounts | to_nice_json }}"
    dest: "{{ (rewardsfarmer_systemd_service_path, rewardsfarmer_accounts_filename) | path_join }}"
    owner: root
    group: root
    mode: "0600"
  when: rewardsfarmer_accounts.accounts | length > 0

- name: Setup SystemD services (service and timer)
  ansible.builtin.include_role:
    name: docker_compose_systemd_service
    tasks_from: systemd
  vars:
    docker_compose_systemd_service_servicename: "{{ rewardsfarmer_systemd_service_name }}"
    docker_compose_systemd_service_timer_delay: "{{ rewardsfarmer_systemd_service_timer_delay }}"
    docker_compose_systemd_service_timer_hours: "{{ rewardsfarmer_systemd_service_timer_hours }}"
    docker_compose_systemd_service_timer_enabled: "{{ rewardsfarmer_systemd_service_timer_enabled | default(true) | bool }}"
  when: rewardsfarmer_systemd_enabled | default(true) | bool
